Yedidim/Controllers/StartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using YedideyChabad.Code;
using System.DirectoryServices.AccountManagement;
using System.Web.Security;
using YedideyChabad.Filters;
using YedideyChabad.Models;
using System.Data;
using MongoDB.Driver.Linq;
using YedideyChabad.Authentication.MongoDB;
using MongoDB.Driver;

namespace YedideyChabad.Controllers
{
    [InitializeSimpleMembership]
    [Authorize]
    public class StartController : Controller
    {
        MongoAuthenticationRepository _a = new MongoAuthenticationRepository();
        private MongoDatabase _db;

        public StartController() {
            _db = _a.GetMongoBatabase();
        }

        //
        // GET: /Start/
        public ActionResult Index()
        {
            //TODO: need to get the loggen in user i a different way
            MongoMembershipProvider m = new MongoMembershipProvider();
            bool isvalidUser = m.ValidateUser(User.Identity.Name, "");

            return View();
        }

        //
        // GET: /Start/GetAll
        public ActionResult GetAll()
        {   
            var collection = _db.GetCollection<Yadid>("Members");

            var yadid = (from y in collection.AsQueryable<Yadid>()
                         where y.OwnerUnique == Globals.OwnerId
                         select y).ToList();

            return View(yadid);
        }

        public ActionResult Select(string member)
        {
            Globals.SelectedMemberId = member;
            return RedirectToAction("Index", "YadidMain", new { id = member });
        }

    }
}

Yedidim/Views/Start/GetAll.cshtml
@model IEnumerable<YedideyChabad.Models.Yadid>
@using YedideyChabad.ViewModels

@{
    ViewBag.Title = "Show All";
    Layout = "~/Views/Shared/_Layout-Loggedin.cshtml";
}

@*<h2>@ViewBag.Title</h2>*@
<table class="tabular-data">
    <tr>
        <td class="side-toolbar">
            @Html.Partial("_Loggedin-Side-Menu", new YedideyChabad.ViewModels.SideMenu())
        </td>
        <td class="page-content">
            <table>
      
                <tr>
                    <th></th>
                    <th>
                        @Html.DisplayNameFor(model => model.FirstName)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.LastName)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.PhoneCellular)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Email)
                    </th>
                    <th></th>
                </tr>

            @foreach (var item in Model) {
                <tr>
                    <td class="table-select">
                        @*@Html.ActionLink("Select", "Select", new { id=item.Id })*@
                        <a href='@Url.Action("Select", "Start", new { member=item._id })' class="ico-font-con icon-view"></a>
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.FirstName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.LastName)
                    </td>
       
                    <td>
                        @Html.DisplayFor(modelItem => item.PhoneCellular)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Email)
                    </td>
                    <td class="delete-member">
                        <a href='' onclick="return false;" itemid="@item._id" class="ico-font-con icon-delete"></a>
                        @*<a href='@Url.Action("Delete", "YadidMain", new { id=item.Id })' class="ico-font-con icon-delete"></a>*@
                    </td>
                </tr>
            }

            </table>            
        </td>
    </tr>
</table>

Yedidim/Views/Start/GetChildren.cshtml
@model IEnumerable<Yedidim.Models.Child>
@using Yedidim.ViewModels

@{
    ViewBag.Title = "GetChildren";
    Layout = "~/Views/Shared/_Layout-Loggedin.cshtml";
}

@*<h2>GetChildren</h2>*@

@Html.Partial("_ActionsMenu", new ActionsMenu{ UseruName = true })

<table class="tabular-data">
    <tr>
        @*<th></th>*@
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Birthday_Jewish)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Birthday_Greg)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Age)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Comments)
        </th>
        <th></th>
        <th></th>
        
    </tr>

@foreach (var item in Model) {

    using (Html.BeginForm("UpdateChild", "Child", new { id = item.Id }, FormMethod.Post, new { @id = "childform" + item.Id }))
    {
    <tr>
        @*<td class="table-select">
            <a href='@Url.Action("Select", "Start", new { id=item.Id })' class="ico-font-con icon-view"></a>
        </td>*@
        <td>
            @Html.TextBoxFor(modelItem => item.Name, new { disabled = "disabled" })
            @Html.ValidationMessageFor(modelItem => item.Name)
        </td>
        <td>            
            @Html.TextBoxFor(modelItem => item.Birthday_Jewish, new { disabled = "disabled" })
            @Html.ValidationMessageFor(modelItem => item.Birthday_Jewish)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Birthday_Greg)    
        </td>
        <td>
            @Html.TextBoxFor(modelItem => item.Age, new { disabled = "disabled" })
            @Html.ValidationMessageFor(modelItem => item.Age)
        </td>
        <td>
            @Html.TextBoxFor(modelItem => item.Comments, new { disabled = "disabled" })
            @Html.ValidationMessageFor(modelItem => item.Comments)
        </td>
        <td>
             <a href='' class="ico-font-con icon-edit"></a>
        </td>
        <td>
            @*@Html.ActionLink("Delete", "Delete", new { id=item.Id })*@
            <a href='' onclick="return false;" itemid="@item.Id" class="ico-font-con icon-delete"></a>
        </td>

    </tr>
    }
}

</table>

Yedidim/Views/Start/Index.cshtml
@model IEnumerable<YedideyChabad.Models.Yadid>

@{
    ViewBag.Title = "yedidim main";
    Layout = "~/Views/Shared/_Layout-Loggedin.cshtml";
}

<div class="start-page-options">
    <ul>
        <li>
            <div class="click-active">
                <a href='@Url.Action("GetAll", "Start")' class="ico-font-con">
                    <div class="icon-group"></div>
                    <div class="text">ידידים</div>
                    <div class="sub-text">צפה, הוסף וערוך ידידים</div>
                </a>
            </div>
        </li>
        <li class="disabled-item">
            <div class="click-active">
                <a href='' onclick="return false;" class="ico-font-con">
                    <div class="icon-action"></div>
                    <div class="text">פעילות</div>
                    <div class="sub-text">שיעורים, פגישות ופעילויות נוספות</div>
                </a>
            </div>
        </li>
        <li class="disabled-item">
            <div class="click-active">
                <a href='' onclick="return false;" class="ico-font-con">
                    <div class="icon-calendar"></div>
                    <div class="text">השבוע</div>
                    <div class="sub-text">אירועים, ימי הולדת ותאריכים נוספים</div>
                </a>
            </div>
        </li>
    </ul>
</div>