Yedidim/Controllers/YadidMainController.cs
    using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using YedideyChabad.Models;
using YedideyChabad.Filters;
using YedideyChabad.Controllers;
using YedideyChabad.Code;
using YedideyChabad.Authentication.MongoDB;
using MongoDB.Driver;
using MongoDB.Driver.Linq;
using MongoDB.Driver.Builders;
using MongoDB.Bson;

namespace YedideyChabad.Controllers
{
    [Authorize]
    public class YadidMainController : Controller
    {
        MongoAuthenticationRepository _a = new MongoAuthenticationRepository();
        private MongoDatabase _db;

        public YadidMainController() {
            _db = _a.GetMongoBatabase();
        }

        
        // GET: /YadidMain/
        /// <summary>
        /// reruen a collection of members
        /// or empty form for new member
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Index(string id)
        {
            if (id != Constants.KEY_ADD_NEW)
            {
                /// edit memberdetails
                var _uoi = new ObjectId(id);
                var _collection = _db.GetCollection<Yadid>("Members");

                var yadid = (from y in _collection.AsQueryable<Yadid>()
                             where y._id == _uoi  && y.OwnerUnique == Globals.OwnerId
                             select y).FirstOrDefault();

                if (yadid == null)
                {
                    return HttpNotFound();
                }

                return View("Index", yadid);
            }
            else
            {
                ///return new user view (empty form)
                return View("Index", new Yadid());
            }
        }

        
        // POST: /YadidMain/Index/5
        /// <summary>
        /// insert new member or update
        /// </summary>
        /// <param name="yadid"></param>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Index(Yadid yadid, string id)
        {
            yadid.OwnerUnique = Globals.OwnerId;

            if (id == Constants.KEY_ADD_NEW)
            {
                //add new user
                if (ModelState.IsValid)
                {  
                    var collection = _db.GetCollection<Yadid>("Members");

                    yadid._id = new ObjectId();

                    collection.Insert(yadid);

                    return RedirectToAction("GetAll", "Start");
                }

                return View(yadid);
            }
            else
            {
                //update state
                if (ModelState.IsValid)
                {
                    yadid._id = new ObjectId(Globals.SelectedMemberId);

                    var collection = _db.GetCollection<Yadid>("Members");
                    collection.Save(yadid);

                    return RedirectToAction("Index");
                }
                return View(yadid);                     
            }
        }
        
        // GET: /YadidMain/Delete/5
        /// <summary>
        /// delete members & children
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Delete(string id)
        {
            var _collMembers = _db.GetCollection<Yadid>("Members");
            var _collChildren = _db.GetCollection<Child>("Children");

            _collMembers.Remove(Query.EQ("_id",new ObjectId(id)));
            _collChildren.Remove(
                Query.And(
                        Query.EQ("OwnerUnique", Globals.OwnerId),
                        Query.EQ("YedidId", new ObjectId(id))
                        )
                    );

            return RedirectToAction("GetAll","Start");
        }


        protected override void Dispose(bool disposing)
        {
            ///MONGO-REPLACE
            
            //db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Yedidim/Views/YadidMain/Create.cshtml
@model Yedidim.Models.Yadid

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Yadid</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.FirstName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.FirstName)
            @Html.ValidationMessageFor(model => model.FirstName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.LastName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.LastName)
            @Html.ValidationMessageFor(model => model.LastName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Gender)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Gender)
            @Html.ValidationMessageFor(model => model.Gender)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.DescendantName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.DescendantName)
            @Html.ValidationMessageFor(model => model.DescendantName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Birthday_Jewish)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Birthday_Jewish)
            @Html.ValidationMessageFor(model => model.Birthday_Jewish)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Birthday_Greg)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Birthday_Greg)
            @Html.ValidationMessageFor(model => model.Birthday_Greg)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.PhoneCellular)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.PhoneCellular)
            @Html.ValidationMessageFor(model => model.PhoneCellular)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Email)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Email)
            @Html.ValidationMessageFor(model => model.Email)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.PositionAtWork)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.PositionAtWork)
            @Html.ValidationMessageFor(model => model.PositionAtWork)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Hobby)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Hobby)
            @Html.ValidationMessageFor(model => model.Hobby)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Personalty)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Personalty)
            @Html.ValidationMessageFor(model => model.Personalty)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Comments)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Comments)
            @Html.ValidationMessageFor(model => model.Comments)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.MerigeDate_Greg)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.MerigeDate_Greg)
            @Html.ValidationMessageFor(model => model.MerigeDate_Greg)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.MerigeDate_Jewish)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.MerigeDate_Jewish)
            @Html.ValidationMessageFor(model => model.MerigeDate_Jewish)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.NumOfChildren)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.NumOfChildren)
            @Html.ValidationMessageFor(model => model.NumOfChildren)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.NumOfChildrenForActivities)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.NumOfChildrenForActivities)
            @Html.ValidationMessageFor(model => model.NumOfChildrenForActivities)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Tradition)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Tradition)
            @Html.ValidationMessageFor(model => model.Tradition)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.FamilyComments)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.FamilyComments)
            @Html.ValidationMessageFor(model => model.FamilyComments)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Home_Street)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Home_Street)
            @Html.ValidationMessageFor(model => model.Home_Street)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Home_Number)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Home_Number)
            @Html.ValidationMessageFor(model => model.Home_Number)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Home_Entrance)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Home_Entrance)
            @Html.ValidationMessageFor(model => model.Home_Entrance)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Home_EconomicStatus)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Home_EconomicStatus)
            @Html.ValidationMessageFor(model => model.Home_EconomicStatus)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Home_Comments)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Home_Comments)
            @Html.ValidationMessageFor(model => model.Home_Comments)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Home_Phone)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Home_Phone)
            @Html.ValidationMessageFor(model => model.Home_Phone)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.PartnerFirstName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.PartnerFirstName)
            @Html.ValidationMessageFor(model => model.PartnerFirstName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.PartnerLastName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.PartnerLastName)
            @Html.ValidationMessageFor(model => model.PartnerLastName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.PartnerGender)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.PartnerGender)
            @Html.ValidationMessageFor(model => model.PartnerGender)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.PartnerDescendantName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.PartnerDescendantName)
            @Html.ValidationMessageFor(model => model.PartnerDescendantName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.PartnerBirthday_Jewish)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.PartnerBirthday_Jewish)
            @Html.ValidationMessageFor(model => model.PartnerBirthday_Jewish)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.PartnerBirthday_Greg)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.PartnerBirthday_Greg)
            @Html.ValidationMessageFor(model => model.PartnerBirthday_Greg)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.PartnerPhoneCellular)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.PartnerPhoneCellular)
            @Html.ValidationMessageFor(model => model.PartnerPhoneCellular)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.PartnerEmail)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.PartnerEmail)
            @Html.ValidationMessageFor(model => model.PartnerEmail)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.PartnerPositionAtWork)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.PartnerPositionAtWork)
            @Html.ValidationMessageFor(model => model.PartnerPositionAtWork)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.PartnerHobby)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.PartnerHobby)
            @Html.ValidationMessageFor(model => model.PartnerHobby)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.PartnerPersonalty)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.PartnerPersonalty)
            @Html.ValidationMessageFor(model => model.PartnerPersonalty)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.PartnerComments)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.PartnerComments)
            @Html.ValidationMessageFor(model => model.PartnerComments)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Yedidim/Views/YadidMain/Delete.cshtml
@model Yedidim.Models.Yadid

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Yadid</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.FirstName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.FirstName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.LastName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.LastName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Gender)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Gender)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.DescendantName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.DescendantName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Birthday_Jewish)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Birthday_Jewish)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Birthday_Greg)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Birthday_Greg)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.PhoneCellular)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.PhoneCellular)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Email)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Email)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.PositionAtWork)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.PositionAtWork)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Hobby)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Hobby)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Personalty)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Personalty)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Comments)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Comments)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.MerigeDate_Greg)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.MerigeDate_Greg)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.MerigeDate_Jewish)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.MerigeDate_Jewish)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.NumOfChildren)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.NumOfChildren)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.NumOfChildrenForActivities)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.NumOfChildrenForActivities)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Tradition)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Tradition)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.FamilyComments)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.FamilyComments)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Home_Street)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Home_Street)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Home_Number)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Home_Number)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Home_Entrance)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Home_Entrance)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Home_EconomicStatus)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Home_EconomicStatus)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Home_Comments)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Home_Comments)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Home_Phone)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Home_Phone)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.PartnerFirstName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.PartnerFirstName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.PartnerLastName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.PartnerLastName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.PartnerGender)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.PartnerGender)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.PartnerDescendantName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.PartnerDescendantName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.PartnerBirthday_Jewish)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.PartnerBirthday_Jewish)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.PartnerBirthday_Greg)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.PartnerBirthday_Greg)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.PartnerPhoneCellular)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.PartnerPhoneCellular)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.PartnerEmail)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.PartnerEmail)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.PartnerPositionAtWork)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.PartnerPositionAtWork)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.PartnerHobby)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.PartnerHobby)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.PartnerPersonalty)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.PartnerPersonalty)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.PartnerComments)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.PartnerComments)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

Yedidim/Views/YadidMain/GetAll.cshtml
@model IEnumerable<Yedidim.Models.Yadid>
@using Yedidim.ViewModels

@{
    ViewBag.Title = "Show All";
    Layout = "~/Views/Shared/_Layout-Loggedin.cshtml";
}

@*<h2>@ViewBag.Title</h2>*@

<table class="tabular-data">
      
    <tr>
        <th></th>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PhoneCellular)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td class="table-select">
            @*@Html.ActionLink("Select", "Select", new { id=item.Id })*@
            <a href='@Url.Action("Select", "Start", new { id=item.Id })' class="ico-font-con icon-view"></a>
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LastName)
        </td>
       
        <td>
            @Html.DisplayFor(modelItem => item.PhoneCellular)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            <a href='' onclick="return false;" itemid="@item.Id" class="ico-font-con icon-delete"></a>
            @*<a href='@Url.Action("Delete", "YadidMain", new { id=item.Id })' class="ico-font-con icon-delete"></a>*@
        </td>
    </tr>
}

</table>